name: Main

on:
  schedule:
    - cron: '0 1 * * *'

jobs:
  make-contribution:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Make daily contribution
        run: |
          echo "==========" >> check.txt
          echo "check date:" >> check.txt
          echo "$(date)" >> check.txt
          echo "==========" >> check.txt
      - name: Commit changes
        uses: EndBug/add-and-commit@v7
        with:
          author_name: "oknehcinv"
          author_email: "potapkorkin@gmail.com"
          message: "test"
          add: "check.txt"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          branch: daily-contribution
          # Set the Git credentials - replace this with your own secrets
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Open pull request
        uses: peter-evans/create-pull-request@v3
        with:
          title: "check"
          commit-message: "check"
          branch: daily-contribution
          base: main
          body: "check."
          token: ${{ secrets.GITHUB_TOKEN }}
